name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 18.x
      - name: install dependencies
        run: npm ci
      - name: build app
        run: npm run build && npm run gh-pages:404
        env:
          PUBLIC_URL: /balance
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1